snowflake:
  baseUrl: https://api.jommer.chat
guildDataService:
  baseUrl: https://api.jommer.chat/guild/data
okta:
  client:
    token: test
    org-url: test
  oauth2:
    issuer: test
    clientId: test
    clientSecret: test
server:
  port: 8083
