snowflake:
  baseUrl: ${snowflake_base_url}
okta:
  client:
    token: ${okta_token}
    org-url: ${okta_org_url}
  oauth2:
    issuer: ${okta_issuer}
    clientId: ${okta_clientId}
    clientSecret: ${okta_clientSecret}
server:
  port: 8083